spring:
  application:
    name: YUa8c9TQN6aD
  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
      chat:
        options:
          model: gpt-4o
          temperature: 0.2
          max-tokens: 300
      embedding:
        options:
          model: text-embedding-3-large
          dimensions: 3072
    vectorstore:
      chroma:
        client:
          host: http://localhost
          port: 8000
        collection-name: vector-store
        initialize-schema: true
