spring:
  application:
    name: YUa8c9TQN6aD
  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
      embedding:
        api-key: ${OPENAI_API_KEY}
        options:
          model: text-embedding-3-large
          dimensions: 1000
      chat:
        options:
          model: gpt-4o
          temperature: 0.7
          max-tokens: 300
    vectorstore:
      chroma:
        client:
          host: http://localhost
          port: 8000
        collection-name: vector-store
        initialize-schema: true
